### ISSUE TITLE
Error when trying to close the CKEditor modal

### ISSUE THREAD

**Issue by varadero** [GoodPHP/grapesjs-plugin-ckeditor5#2]
This plugin (this one in `dist` folder) relies on the presence of variable named `editor` in the global `window` object. This has to be removed fixed - `editor.Modal.close()`.

The sample code in the repository does not provide correct information - the blocks list is empty and the user cannot actually test the plug in. I needed to install and use `gjs-preset-webpage` grapesjs plug in to actually make the sample workable.

How to reproduce:
- Use the sample code provided in this repository (but also add `gjs-preset-webpage` - see how to in the official grapesjs page grapesjs.com )
- Modify the `index.html` page renaming `var editor = grapesjs.init(...` to `var abc = grapesjs.init(...` (because we don't use hard coded names in our code)
- Drag and drop text block and double click it to show the modal editor
- Click on "Save" (or "Close") button

What happens:

The modal editor is not closed. Error is shown in the browser console:
```
(index):1 Uncaught ReferenceError: editor is not defined
    at HTMLInputElement.onclick
```

The error is because the plugin code in the `dist` folder relies on the presence of variable named `editor` in the `window` object.

**Comment by GoodPHP** [comment]
GIT was updated, please check
Thanks!
