### ISSUE TITLE
Many same HTML elements are created when modal editor is opened

### ISSUE THREAD

**Issue by varadero** [GoodPHP/grapesjs-plugin-ckeditor5#4]
What I observed in the HTML is that when I click multiple times on a text and modal ckeditor is opened, many same HTML elements are created:

![image](https://user-images.githubusercontent.com/7610713/171805833-52bc0094-202f-4d8d-8256-3517dffcd88d.png)

**Comment by GoodPHP** [comment]
GIT was updated, please check
Thanks!
